version: '3.3'

services:
    nginx:
        build: ./nginx/.
        env_file:
            - .env
        ports:
            - "8080:80"
        volumes:
            - "./code:${PROJECT_DIR}"
        links:
            - php
    php:
        build: ./php/.
        env_file:
            - .env
        volumes:
            - "./code:${PROJECT_DIR}"
    mysql:
        build: ./mysql/.
        restart: always
        env_file:
            - .env
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/init/create.sql:/docker-entrypoint-initdb.d/create.sql
            - ./mysql/init/custom.cnf:/etc/mysql/conf.d/custom.cnf
volumes:
    mysql:
        driver: "local"
